name: spacex_api
description: Dart package for using SpaceX API
version: 0.0.1
author:
homepage: 'TBD'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.2

dev_dependencies:
  test: ^1.15.5
