name: spacex_api
description: Dart wrapper for unofficial SpaceX API v4, providing information about everything related to SpaceX and its public data.
version: 0.0.5
homepage: 'https://github.com/ahsanz024/spacex_api'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0

dev_dependencies:
  test: ^1.15.5
