name: spacex_api
description: Dart package for using SpaceX API (v4)
version: 0.0.2
homepage: 'https://github.com/ahsanz024/spacex_api'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.2

dev_dependencies:
  test: ^1.15.5
