name: spacex_api
description: Dart wrapper for unofficial SpaceX API v4 (with support for all endpoints and query subsystem in Dart), providing information about everything related to SpaceX and its public data.
version: 0.0.4
homepage: 'https://github.com/ahsanz024/spacex_api'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.2

dev_dependencies:
  test: ^1.15.5
