class SpaceTrack {
  late String _cCSDSOMMVERS;
  late String _cOMMENT;
  late String _cREATIONDATE;
  late String _oRIGINATOR;
  late String _oBJECTNAME;
  late String _oBJECTID;
  late String _cENTERNAME;
  late String _rEFFRAME;
  late String _tIMESYSTEM;
  late String _mEANELEMENTTHEORY;
  late String _ePOCH;
  late num _mEANMOTION;
  late num _eCCENTRICITY;
  late num _iNCLINATION;
  late num _rAOFASCNODE;
  late num _aRGOFPERICENTER;
  late num _mEANANOMALY;
  late num _ePHEMERISTYPE;
  late String _cLASSIFICATIONTYPE;
  late num _nORADCATID;
  late num _eLEMENTSETNO;
  late num _rEVATEPOCH;
  late num _bSTAR;
  late num _mEANMOTIONDOT;
  late num _mEANMOTIONDDOT;
  late num _sEMIMAJORAXIS;
  late num _pERIOD;
  late num _aPOAPSIS;
  late num _pERIAPSIS;
  late String _oBJECTTYPE;
  late String _rCSSIZE;
  late String _cOUNTRYCODE;
  late String _lAUNCHDATE;
  late String _sITE;
  late String _dECAYDATE;
  late num _dECAYED;
  late num _fILE;
  late num _gPID;
  late String _tLELINE0;
  late String _tLELINE1;
  late String _tLELINE2;

  SpaceTrack();

  // ...

  SpaceTrack.fromJson(Map<String, dynamic> json) {
    _cCSDSOMMVERS = json['CCSDS_OMM_VERS'];
    _cOMMENT = json['COMMENT'];
    _cREATIONDATE = json['CREATION_DATE'];
    _oRIGINATOR = json['ORIGINATOR'];
    _oBJECTNAME = json['OBJECT_NAME'];
    _oBJECTID = json['OBJECT_ID'];
    _cENTERNAME = json['CENTER_NAME'];
    _rEFFRAME = json['REF_FRAME'];
    _tIMESYSTEM = json['TIME_SYSTEM'];
    _mEANELEMENTTHEORY = json['MEAN_ELEMENT_THEORY'];
    _ePOCH = json['EPOCH'];
    _mEANMOTION = json['MEAN_MOTION'];
    _eCCENTRICITY = json['ECCENTRICITY'];
    _iNCLINATION = json['INCLINATION'];
    _rAOFASCNODE = json['RA_OF_ASC_NODE'];
    _aRGOFPERICENTER = json['ARG_OF_PERICENTER'];
    _mEANANOMALY = json['MEAN_ANOMALY'];
    _ePHEMERISTYPE = json['EPHEMERIS_TYPE'];
    _cLASSIFICATIONTYPE = json['CLASSIFICATION_TYPE'];
    _nORADCATID = json['NORAD_CAT_ID'];
    _eLEMENTSETNO = json['ELEMENT_SET_NO'];
    _rEVATEPOCH = json['REV_AT_EPOCH'];
    _bSTAR = json['BSTAR'];
    _mEANMOTIONDOT = json['MEAN_MOTION_DOT'];
    _mEANMOTIONDDOT = json['MEAN_MOTION_DDOT'];
    _sEMIMAJORAXIS = json['SEMIMAJOR_AXIS'];
    _pERIOD = json['PERIOD'];
    _aPOAPSIS = json['APOAPSIS'];
    _pERIAPSIS = json['PERIAPSIS'];
    _oBJECTTYPE = json['OBJECT_TYPE'];
    _rCSSIZE = json['RCS_SIZE'];
    _cOUNTRYCODE = json['COUNTRY_CODE'];
    _lAUNCHDATE = json['LAUNCH_DATE'];
    _sITE = json['SITE'];
    _dECAYDATE = json['DECAY_DATE'];
    _dECAYED = json['DECAYED'];
    _fILE = json['FILE'];
    _gPID = json['GP_ID'];
    _tLELINE0 = json['TLE_LINE0'];
    _tLELINE1 = json['TLE_LINE1'];
    _tLELINE2 = json['TLE_LINE2'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['CCSDS_OMM_VERS'] = this._cCSDSOMMVERS;
    data['COMMENT'] = this._cOMMENT;
    data['CREATION_DATE'] = this._cREATIONDATE;
    data['ORIGINATOR'] = this._oRIGINATOR;
    data['OBJECT_NAME'] = this._oBJECTNAME;
    data['OBJECT_ID'] = this._oBJECTID;
    data['CENTER_NAME'] = this._cENTERNAME;
    data['REF_FRAME'] = this._rEFFRAME;
    data['TIME_SYSTEM'] = this._tIMESYSTEM;
    data['MEAN_ELEMENT_THEORY'] = this._mEANELEMENTTHEORY;
    data['EPOCH'] = this._ePOCH;
    data['MEAN_MOTION'] = this._mEANMOTION;
    data['ECCENTRICITY'] = this._eCCENTRICITY;
    data['INCLINATION'] = this._iNCLINATION;
    data['RA_OF_ASC_NODE'] = this._rAOFASCNODE;
    data['ARG_OF_PERICENTER'] = this._aRGOFPERICENTER;
    data['MEAN_ANOMALY'] = this._mEANANOMALY;
    data['EPHEMERIS_TYPE'] = this._ePHEMERISTYPE;
    data['CLASSIFICATION_TYPE'] = this._cLASSIFICATIONTYPE;
    data['NORAD_CAT_ID'] = this._nORADCATID;
    data['ELEMENT_SET_NO'] = this._eLEMENTSETNO;
    data['REV_AT_EPOCH'] = this._rEVATEPOCH;
    data['BSTAR'] = this._bSTAR;
    data['MEAN_MOTION_DOT'] = this._mEANMOTIONDOT;
    data['MEAN_MOTION_DDOT'] = this._mEANMOTIONDDOT;
    data['SEMIMAJOR_AXIS'] = this._sEMIMAJORAXIS;
    data['PERIOD'] = this._pERIOD;
    data['APOAPSIS'] = this._aPOAPSIS;
    data['PERIAPSIS'] = this._pERIAPSIS;
    data['OBJECT_TYPE'] = this._oBJECTTYPE;
    data['RCS_SIZE'] = this._rCSSIZE;
    data['COUNTRY_CODE'] = this._cOUNTRYCODE;
    data['LAUNCH_DATE'] = this._lAUNCHDATE;
    data['SITE'] = this._sITE;
    data['DECAY_DATE'] = this._dECAYDATE;
    data['DECAYED'] = this._dECAYED;
    data['FILE'] = this._fILE;
    data['GP_ID'] = this._gPID;
    data['TLE_LINE0'] = this._tLELINE0;
    data['TLE_LINE1'] = this._tLELINE1;
    data['TLE_LINE2'] = this._tLELINE2;
    return data;
  }
}
